config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  scope "/:locale" do
    devise_for :users
    scope "/admin" do
      resources :users, except: 'show'
    end
    resources :cities do
      resources :pictures
      resources :squats do
        member do
          get 'version/:version_id', action: :version, as: 'version'
          get 'revert_to_version/:version_id', action: :revert_to_version, as: 'revert_to_version'
        end
        collection do
          get 'unpublished'
        end
      end
    end
    resources :comments do#, except: [:index, :show, :new]
      collection do
        post 'bulk_delete'
      end
    end
  end

end

app/models/city.rb
class City < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_and_belongs_to_many :users
  has_many :squats
  has_many :pictures, through: :squats
  has_many :comments, as: :commentable

  validates :slug,
            presence: true,
            uniqueness: true

  validates :lat,
            :lng,
            presence: true

  has_paper_trail

  scope :by_name, -> { order(:name) }

  enum label_position: { bottom: 0, right: 1, top: 2 }

  def latlng
    lat && lng ? [lat, lng] : nil
  end

  def squat_bounds
    if squats.count <= 1
      nil
    else
      [
        [ squats.published.minimum(:lat),
          squats.published.minimum(:lng)],
        [ squats.published.maximum(:lat),
          squats.published.maximum(:lng)]
      ]
    end
  end

  def menu_name
    if external_url.blank?
      "#{name} (#{squats.published.count})"
    else
      name
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

  validates :title, :email, :body, :commentable, presence: true

  def city
    if commentable.class == City
      commentable
    else
      commentable.city
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_commentable_from_params, only: [:new, :create]
  before_action :set_commentable, except: [:new, :create, :index, :bulk_delete]

  load_and_authorize_resource

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def bulk_delete
    Comment.where(id: params['comment_ids']).destroy_all
    redirect_to comments_path
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    @comment.commentable = @commentable
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.email ||= current_user.email
    if @comment.save
      recipients = @comment.city.users.pluck(:email)
      NotificationsMailer.comment_notification(recipients, @comment).deliver_now
      respond_with(@comment)
    else
      render :edit
    end
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_commentable_from_params
      type = params[:comment][:commentable_type]
      id   = params[:comment][:commentable_id]
      @commentable = type.constantize.find(id)
    end

    def set_commentable
      @commentable = @comment.commentable
    end

    def comment_params
      params.require(:comment).permit(:title, :body, :email, :published, :commentable_id, :commentable_type)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def commentable_path(commentable)
    if commentable.class == City
      city_path commentable
    elsif commentable.class == Squat
      city_squat_path commentable.city, commentable
    end
  end

end

app/views/comments/edit.html.haml
%h1
  = t(:edit_comment_for)
  = @commentable.name

= simple_form_for(@form, as: :comment, url: comment_path(@comment)) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, label: t(:title)
    = f.input :body, label: t(:body)
    = f.input :email

  .form-actions.btn-group
    = f.button :submit, value: t(:update)
    - if can? :delete, @comment
      = link_to t(:destroy), @comment, method: :delete, data: { confirm: t(:confirm_question) }, class: 'btn btn-danger'
    - if can? :update, @comment
      = link_to t(:back), comments_path, class: 'btn btn-default'

app/views/comments/index.html.haml
%h1
  = Comment.model_name.human(count: Comment.all.count)

= form_tag(bulk_delete_comments_path) do
  %table.table.table-striped
    %thead
      %tr
        %th
        %th Title
        %th Body
        %th Comment on
        %th Type
        %th Email

    %tbody
      - @comments.each do |comment|
        %tr
          %td= check_box_tag 'comment_ids[]', comment.id if can? :bulk_delete, Comment
          %td= link_to comment.title, comment
          %td= truncate comment.body
          %td= link_to comment.commentable.name, commentable_path(comment.commentable)
          %td= comment.commentable.class
          %td
            - if can? :view_email, comment
              = comment.email

  - if can? :bulk_delete, Comment
    = submit_tag 'Delete selected',
                 data: { confirm: 'Are you sure you want to delete all of these comments?' },
                 class: 'btn btn-danger'

app/views/comments/new.html.haml
%h1
  = t(:new_comment_for)
  = @commentable.name

= simple_form_for(@form, as: :comment, url: comments_path ) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, label: t(:title)
    = f.input :body, label: t(:body)
    = f.input :email
    = f.input :commentable_id, as: :hidden
    = f.input :commentable_type, as: :hidden

  .form-actions.btn-group
    = f.button :submit, value: t(:create)
    - if can? :update, @comment
      = link_to t(:back), comments_path, class: 'btn btn-default'

app/views/comments/show.html.haml
%p#notice= notice

%h1= @comment.title

.comment-body= auto_link(@comment.body, link: :urls)

- if can? :view_email, @comment
  %p
    %b Email:
    = @comment.email

%p
  %b
    Comment on:
    = link_to @comment.commentable.name, commentable_path(@comment.commentable)
    = @comment.commentable.class

.form-actions.btn-group
  - if can? :update, @comment
    = link_to t(:edit), edit_comment_path(@comment), class: 'btn btn-primary'
  - if can? :destroy, @comment
    = link_to t(:destroy), @comment, :method => :delete, :data => { :confirm => t(:confirm_question) }, class: 'btn btn-danger'
  = link_to t(:back), comments_path, class: 'btn btn-default'