config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  scope "/:locale" do
    devise_for :users
    scope "/admin" do
      resources :users, except: 'show'
    end
    resources :cities do
      resources :pictures
      resources :squats do
        member do
          get 'version/:version_id', action: :version, as: 'version'
          get 'revert_to_version/:version_id', action: :revert_to_version, as: 'revert_to_version'
        end
        collection do
          get 'unpublished'
        end
      end
    end
    resources :comments do#, except: [:index, :show, :new]
      collection do
        post 'bulk_delete'
      end
    end
  end

end

app/models/squat.rb
class Squat < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  attr_accessor :current_user

  TAGS = [
    'uncertain_date',
    'uncertain_location',
    'social_center',
    'self_evicted',
    'occupied_public_space',
    'caravan_site'
  ]

  belongs_to :city
  has_and_belongs_to_many :pictures
  has_many :periods, dependent: :destroy
  has_many :comments, as: :commentable

  serialize :tags, JSON

  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }

  validates :name,
            :lat,
            :lng,
            presence: true

  validates :slug,
            presence: true,
            uniqueness: true

  validates :external_user_email,
            presence: true,
            if: Proc.new { current_user.nil? }

  validates_associated :periods

  # has at least one period
  validate do
    errors.add(:base, I18n.t(:at_least_one_period_error)) if periods.reject(&:marked_for_destruction?).empty?
  end

  # has location
  validate do
    errors.add(:base, I18n.t(:location_required)) if lat.nil? or lng.nil?
  end

  # no overlapping periods
  validate do
    periods.each do |p1|
      periods.reject{ |p| p == p1 }.each do |p2|
        if p2.start_year > p1.start_year && p1.end_year.present? && p2.start_year < p1.end_year
          errors.add(:base, I18n.t(:overlapping_periods_error))
        end
      end
    end
  end

  # no two open ended periods
  validate do
    if periods.select{ |p| p.end_year.blank? }.size > 1
      errors.add(:base, I18n.t(:two_open_ended_periods_error))
    end
  end

  validate do
    if !link.blank? and not %w( http https ).include?(URI.parse(link).scheme)
      errors.add(:link, I18n.t(:invalid_link_url))
    end
  end

  before_save :clean_tags

  accepts_nested_attributes_for :periods, allow_destroy: true

  has_paper_trail

  def self.form_tags
    TAGS.map { |tag| [I18n.t(tag), tag] }
  end

  def clean_tags
    tags.reject! { |t| t.blank? } if tags.present?
  end

  def latlng
    lat && lng ? [lat, lng] : nil
  end

  def full_address
    [address, address_city].reject(&:blank?).join(", ")
  end

end

app/controllers/squats_controller.rb
class SquatsController < ApplicationController
  before_action :set_city

  load_and_authorize_resource except: [:new, :create]

  respond_to :html, :json, :kml, :xlsx

  def index
    if @city.external_url.present?
      redirect_to @city.external_url
    else
      @squats_url = city_squats_path(@city, format: :json)
      @squats = @city.squats
                     .published
                     .includes(:periods)
                     .includes(:pictures)
                     .order(:name)
      respond_with(@squats) do |format|
        format.xlsx do
          response.headers['Content-Disposition'] = "attachment; filename=\"#{@city.slug}_squats.xlsx\""
        end
      end
    end
  end

  def unpublished
    @squats_url = unpublished_city_squats_path(@city, format: :json)
    @squats = @city.squats
                   .unpublished
                   .includes(:periods)
                   .includes(:pictures)
                   .order(:name)
    respond_with(@squats, template: 'squats/index')
  end

  def show
    respond_with(@squat)
  end

  def new
    @squat = Squat.new
    @squat.periods.build
    @squat.address_city = @city.name
    authorize! :create, @squat, @city
    respond_with(@squat)
  end

  def edit
  end

  def create
    @squat = Squat.new(squat_params)
    authorize! :create, @squat, @city

    @squat.city = @city
    @squat.current_user = current_user
    @squat.published = current_user.present?

    if @squat.save
      if current_user.nil?
        recipients = @city.users.pluck(:email)
        NotificationsMailer.squat_notification(recipients, @squat).deliver_now
        flash[:notice] = t(:squat_submitted_for_review)
      else
        flash[:notice] = t(:squat_created)
      end
    end
    respond_with(@city, @squat)
  end

  def update
    @squat.current_user = current_user
    if @squat.update(squat_params)
      flash[:notice] = t(:squat_updated)
      redirect_to city_squats_path(@city, anchor: @squat.slug)
    else
      render 'edit'
    end
  end

  def destroy
    @squat.destroy
    respond_with(@city, @squat)
  end

  def version
    authorize! :read, PaperTrail::Version
    @squat = @squat.versions.select{ |version| version.id == params[:version_id].to_i }.first.reify
    render 'show'
  end

  def revert_to_version
    authorize! :read, PaperTrail::Version
    @version = @squat.versions.select{ |version| version.id == params[:version_id].to_i }.first.reify
    @version.save
    redirect_to city_squat_path(@city, @version)
  end

  private

    def set_city
      @city = City.friendly.find(params[:city_id])
    end

    def squat_params
      params.require(:squat).permit(
        :name, :body, :link, :address, :address_city, :lat, :lng, :external_user_email, :published,
        tags: [],
        periods_attributes: [:id,
          :start_year, :start_month, :start_day,
          :end_year, :end_month, :end_day,
          :_destroy
        ]
      )
    end
end

app/helpers/squats_helper.rb
module SquatsHelper

  def squat_get_icon(squat)
    # temp fix for squats without periods
    if squat.periods.count == 0 || squat.periods.first.start_year.nil?
      return asset_path "svg/haus_grau.svg"
    end

    start_decade = [squat.periods.first.start_year / 10 * 10, 1960].max
    evicted = squat.periods.last.end_year.present?

    if squat.tags.try(:include?, 'caravan_site')
      base = 'wagen'
    elsif squat.tags.try(:include?, 'occupied_public_space')
      base = 'zelt'
    else
      base = 'haus'
    end

    filename = "#{ base }_#{ start_decade }"

    if evicted
      filename += '_evicted'
    end

    if squat.tags.try(:include?, 'social_center')
      filename += '_sc'
    end

    asset_path "svg/#{ filename }.svg"
  end

end

app/views/squats/_description.html.haml
- if squat.address != squat.name
  = simple_format squat.full_address, {}, wrapper_tag: "address"

.periods.squat-info
  %h5= t(:squat_period)
  - squat.periods.each do |p|
    .period
      = simple_format p.to_s

-unless squat.tags.blank?
  .tags.squat-info
    %h5= t(:tags)
    %ul
      - squat.tags.try(:each) do |tag|
        %li= t(tag.to_sym)

.body= sanitize squat.body

- if squat.link
  = link_to squat.link, squat.link, class: :link, target: '_blank'

-unless squat.pictures.blank?
  .pictures.squat-info
    %h5= t(:pictures)
    - squat.pictures.each do |picture|
      %figure.picture
        = link_to(request.protocol + request.host_with_port + picture.picture_url, data: { lightbox: 'picture', title: picture.title }) do
          = image_tag(request.protocol + request.host_with_port + picture.picture_url(:thumb), size: '95x95')
        %figcaption
          = can?(:update, Picture) ? link_to(picture.title, city_picture_path(squat.city, picture)) : picture.title

= render partial: 'shared/comments', locals: { commentable: squat, show_create_comment_link: show_create_comment_link }

app/views/squats/_form.html.haml
= simple_nested_form_for([@city, @squat]) do |f|
  = render 'shared/error_messages', object: f.object

  .form-inputs
    = f.input :name

    - if @squat.id && !@squat.published
      .alert.alert-danger
        = t(:not_published)
    - if @squat.id?
      = f.input :published, label: t(:published)

    - if @squat.id?
      #map{ data: { mode: :edit, latlng: @squat.latlng, zoom: 14, icon: get_default_icon } }
    - else
      #map{ data: { mode: :create, latlng: @city.latlng, zoom: 10, icon: get_default_icon } }

    .row
      .col-md-8
        = f.input :address, as: :text
        = f.input :address_city, label: t(:address_city)
      .col-md-4
        %label(style='display: block')
          &nbsp;
        %a.btn.btn-default#geocode{'data-sources': ['#squat_address', '#squat_address_city']}
          = t(:geocode_address)

    #geocode-error.alert.alert-danger(style="display:none")
      = t(:geocode_error)

    .row
      .col-md-4
        = f.input :lat, label: t(:latitude), as: :string
      .col-md-4
        = f.input :lng, label: t(:longitude), as: :string
      .col-md-4
        %label(style='display: block')
          &nbsp;
        %a.btn.btn-default#set-lat-lng
          = t(:set_lat_lng)

    = tinymce_assets
    = f.text_area :body, class: 'tinymce', rows: 20, cols: 120, label: t(:label_body)
    = tinymce

    = f.input :link, as: :string

    #periods.well
      %h2= t(:squat_period)
      = f.simple_fields_for :periods do |p|
        .period.row
          .col-md-1
            = p.input :start_day, collection: (1..31).to_a
          .col-md-2
            = p.input :start_month, collection: (1..12).to_a.map{|i| [I18n.t("date.month_names")[i], i]}
          .col-md-2
            = p.input :start_year
          .col-md-1
            = p.input :end_day, collection: (1..31).to_a
          .col-md-2
            = p.input :end_month, collection: (1..12).to_a.map{|i| [I18n.t("date.month_names")[i], i]}
          .col-md-2
            = p.input :end_year
          .col-md-2
            %label(style='display: block')
              &nbsp;
            = p.link_to_remove t(:remove_period), data: { confirm: t(:confirm_question) }, class: "pull-right btn btn-danger btn-xs"
      = f.link_to_add t(:add_period), :periods, class: "btn btn-primary btn-xs"

    = f.input :tags, collection: Squat.form_tags, as: :check_boxes, label: t(:tags)

    - if current_user.nil?
      .well
        = f.input :external_user_email, label: 'Email address for questions'
    - elsif @squat.try(:external_user_email)
      .form-group
        %label.control-label
          External User Email
        %div
          %p.form-control-static
            = @squat.try(:external_user_email)

  .form-actions.btn-group
    = f.button :submit, value: (@squat.id? ? t(:update_squat) : t(:create_squat)), class: "btn btn-default"
    - if @squat.id?
      = link_to t(:destroy), [@city, @squat], :method => :delete, :data => { :confirm => t(:confirm_question) }, class: "btn btn-default"
      = link_to t(:show), [@city, @squat], class: "btn btn-default"
    = link_to t(:back_to_city), city_squats_path(@city, anchor: @squat.slug), class: "btn btn-default"

app/views/squats/_menu.html.haml
- content_for :menu_left do
  %li.dropdown
    %a.dropdown-toggle{ href:"#", "data-toggle" => "dropdown", role: "button", "aria-expanded" => "false" }
      = @city.name
      %span.caret
    %ul.dropdown-menu{ role: "menu" }
      %li
        %a.dynamic_menu{href: "#city_text"}= t(:info_text)
      %li
        %a.dynamic_menu{href: "#squat_list"}= Squat.model_name.human(:count => 2)
      %li= link_to t(:pictures), city_pictures_path(@city)
      - if can?(:update, City)
        %li.divider
        %li= link_to t(:change_city_info), edit_city_path(@city)
      - if can? :create, Squat.new, @city
        %li.divider
        %li= link_to t(:new_squat), new_city_squat_path(@city)
      - if can? :create, Picture
        %li.divider
        %li= link_to t(:upload_picture), new_city_picture_path(@city)
      - if current_user
        %li.divider
        %li= link_to "#{t(:not_published)} (#{@city.squats.unpublished.count})", unpublished_city_squats_path(@city)
      %li.divider
      %li= link_to 'Download KML', city_squats_path(format: :kml)
      %li= link_to 'Download XLS', city_squats_path(format: :xlsx)

app/views/squats/_popup.html.haml
%h4= squat.name

- if can? :update, squat
  = link_to t(:edit_squat), edit_city_squat_path(squat.city, squat), class: 'btn btn-primary btn-xs'

- if can? :create, Picture
  = link_to t(:upload_picture), new_city_picture_path(squat.city, squat_id: squat.id), class: "btn btn-primary btn-xs"

= render partial: "description", locals: { squat: squat, show_create_comment_link: true }

app/views/squats/edit.html.haml
%h1
  = t(:editing_squat)

= render 'form'

app/views/squats/index.html.haml
- content_for :container_class do
  container-fluid

= render("menu")

%a#legend-label.toggle-label
  = t(:legend)

= render("shared/legend")

#sidebar.full-height
  .sidebar-outer-content
    %i#close_sidebar.glyphicon.glyphicon-remove.pull-right
    #squat_list.sidebar-content
      %h2= Squat.model_name.human(:count => 2)
      - @squats.group_by{ |u| u.name.upcase[0] }.each do |alpha, squats|
        %h3= alpha
        %ul
          - squats.each do |squat|
            %li
              %a{href: '#' + squat.slug}= squat.name
    #city_text.sidebar-content
      %h2= @city.name
      = sanitize @city.body
      = render partial: 'shared/comments', locals: { commentable: @city, show_create_comment_link: true }

#map.full-height{ data: { squats_url: @squats_url, mode: :index, latlng: @city.latlng, bounds: @city.squat_bounds, zoom: 10 } }

- content_for :footer do
  %a#filter-label.toggle-label
    Filter
  %nav#footer.navbar.navbar-default.navbar-fixed-bottom.hidden
    .container-fluid
      .row
        #all_years_container
          %input#all_years{type: :checkbox, title: t(:all_years), checked: true}
          %br
          %label{ for: "all_years"}
            = t(:all_years)
        #slider_container
          #slider{ data: { from: city_start_year(@city), to: Date.today.year } }
          #year
            = t(:all_years)
      .row
        - Squat.form_tags.each do |name, key|
          .tag-filter
            = check_box_tag key
            = label_tag key, name

app/views/squats/index.kml.erb
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
  <% @squats.each do |squat| %>
  <Placemark>
    <name><%= squat.name %></name>
    <description><%=
      Nokogiri::HTML::fragment(render({
        partial: 'squats/description',
        formats: [:html],
        locals:  { squat: squat, show_create_comment_link: false }
      })).to_xml.html_safe
    %></description>
    <Point>
      <coordinates><%= squat.lng %>,<%= squat.lat %></coordinates>
    </Point>
  </Placemark>
  <% end %>
</Document>
</kml>

app/views/squats/new.html.haml
%h1
  =t(:new_squat)

= render 'form'

app/views/squats/show.html.haml
%h1= @squat.name

- if !@squat.published
  .alert.alert-danger
    = t(:not_published)

#map{ data: { squats_url: city_squat_url(@city, @squat, format: :json), mode: :show, latlng: @squat.latlng, zoom: 14 } }

= render partial: "description", locals: { squat: @squat, show_create_comment_link: false }

- if current_user.present?
  .external_user_email.squat-info
    %h5= t(:external_user_email)
    = @squat.external_user_email

.btn-group
  - if can? :update, @squat
    = link_to t(:edit), edit_city_squat_path(@city, @squat), class: "btn btn-default"
  - if can? :create, Picture
    = link_to t(:upload_picture), new_city_picture_path(@city, squat_id: @squat.id), class: "btn btn-default"
  - if can?(:create, Comment)
    = link_to t(:new_comment), new_comment_path(comment: { commentable_id: @squat.id, commentable_type: @squat.class }), class: 'btn btn-default'
  = link_to t(:back_to_city), city_squats_path(@city, anchor: @squat.slug), class: "btn btn-default"

= render partial: "shared/versions", locals: {record: @squat}