config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  scope "/:locale" do
    devise_for :users
    scope "/admin" do
      resources :users, except: 'show'
    end
    resources :cities do
      resources :pictures
      resources :squats do
        member do
          get 'version/:version_id', action: :version, as: 'version'
          get 'revert_to_version/:version_id', action: :revert_to_version, as: 'revert_to_version'
        end
        collection do
          get 'unpublished'
        end
      end
    end
    resources :comments do#, except: [:index, :show, :new]
      collection do
        post 'bulk_delete'
      end
    end
  end

end

app/models/city.rb
class City < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_and_belongs_to_many :users
  has_many :squats
  has_many :pictures, through: :squats
  has_many :comments, as: :commentable

  validates :slug,
            presence: true,
            uniqueness: true

  validates :lat,
            :lng,
            presence: true

  has_paper_trail

  scope :by_name, -> { order(:name) }

  enum label_position: { bottom: 0, right: 1, top: 2 }

  def latlng
    lat && lng ? [lat, lng] : nil
  end

  def squat_bounds
    if squats.count <= 1
      nil
    else
      [
        [ squats.published.minimum(:lat),
          squats.published.minimum(:lng)],
        [ squats.published.maximum(:lat),
          squats.published.maximum(:lng)]
      ]
    end
  end

  def menu_name
    if external_url.blank?
      "#{name} (#{squats.published.count})"
    else
      name
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  ROLES = { 'Admin' => 'admin', 'User' => 'user' }

  validates :role, inclusion: { in: ROLES.values }

  has_and_belongs_to_many :cities

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #
  # Removed default modules:
  # :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      respond_with(@user)
    end
  end

  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update(user_params)
      redirect_to users_path
    else
      respond_with(@user)
    end
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def user_params
      params.require(:user).permit(:email, :role, :password, :password_confirmation, city_ids: [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :role, collection: User::ROLES
    = f.association :cities, as: :check_boxes

    = f.input :password
    = f.input :password_confirmation
    .alert.alert-info
      Leave both password fields blank if you dont want to change it

  .form-actions.btn-group
    = f.button :submit
    - if @user.persisted?
      = link_to 'Destroy', @user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
    = link_to 'Back', users_path, class: 'btn btn-default'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

%h2
  User stats

%table.table.striped
  %tr
    %th Edits
    %td= PaperTrail::Version.where(whodunnit: @user.id).count
  %tr
    %th Edited squats by city
    - squat_ids = PaperTrail::Version.where(whodunnit: @user.id, item_type: 'Squat').select(:item_id).distinct
    - city_ids = Squat.where(id: squat_ids).select(:city_id).distinct
    - cities = City.where(id: city_ids)
    %td
      %table.table
        - cities.each do |city|
          %tr
            %td= link_to(city.name, city_squats_path(city))
            %td= Squat.where(id: squat_ids, city: city).count

app/views/users/index.html.haml
%h1 Listing users

%table.table.table-striped
  %thead
    %tr
      %th Email
      %th Role
      %th Cities

  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.email, edit_user_path(user)
        %td= user.role
        %td= user.cities.map(&:name).join(', ')

%br

= link_to 'New User', new_user_path, class: 'btn btn-primary'

app/views/users/new.html.haml
%h1 New user

= render 'form'