config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  scope "/:locale" do
    devise_for :users
    scope "/admin" do
      resources :users, except: 'show'
    end
    resources :cities do
      resources :pictures
      resources :squats do
        member do
          get 'version/:version_id', action: :version, as: 'version'
          get 'revert_to_version/:version_id', action: :revert_to_version, as: 'revert_to_version'
        end
        collection do
          get 'unpublished'
        end
      end
    end
    resources :comments do#, except: [:index, :show, :new]
      collection do
        post 'bulk_delete'
      end
    end
  end

end

app/views/shared/_comments.html.haml
-unless commentable.comments.blank?
  .comments
    %h5= Comment.model_name.human(count: commentable.comments.count)
    %ul
      - commentable.comments.try(:each) do |comment|
        %li
          - if can? :edit, comment
            %b= link_to comment.title, edit_comment_path(comment)
          -else
            %b= comment.title
          .comment-body= auto_link(comment.body, link: :urls)

- if can?(:create, Comment) && show_create_comment_link
  = link_to t(:new_comment), new_comment_path(comment: { commentable_id: commentable.id, commentable_type: commentable.class }), class: 'btn btn-default btn-xs'

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-danger
    = t(:error_message)
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{class: "alert fade-in #{bootstrap_class_for(type)}" }
    %button.close{ data: { dismiss: "alert" } }
      ×
    = message
- flash.clear

app/views/shared/_layout.html.haml
!!!
%html
  %head
    %title Squatting Europe Kollective
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"}
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

    =# javascript_include_tag 'https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.js'
    =# stylesheet_link_tag    'https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.css', media: 'all'
    = csrf_meta_tags
  %body
    = render 'shared/menu'
    %div#main{class: (content_for?(:container_class) ? yield(:container_class) : "container") }
      = render 'shared/flash_messages', flash: flash
      = yield
    = yield(:footer)

app/views/shared/_legend.html.haml
#legend.hidden
  %table
    %tr
      %th
        = t(:legend)
        %i#close_legend.glyphicon.glyphicon-remove.pull-right
    %tr
      %th
        = t(:squatted_after)
    %tr
      %td
        %table(style="width:100%")
          %tbody
            %tr
              - LegendColors.until_now.values.each do |color|
                %td.year-color(style="background-color:#{color}")
            %tr
              - LegendColors.until_now.keys.each do |year|
                %td
                  = year
    %tr
      %td
        %table
          %tbody
            %tr
              %td
                = image_tag( "svg/haus_grau.svg", style: "width:22px;height:32px;" )
              %td
                = image_tag( "svg/wagen_grau.svg", style: "width:22px;height:32px;" )
              %td
                = image_tag( "svg/zelt_grau.svg", style: "width:22px;height:32px;" )
              %td
                = image_tag( "svg/haus_grau_evicted.svg", style: "width:22px;height:32px;" )
            %tr
              %td(style="width:25%;")
                = t(:house)
              %td(style="width:25%;")
                = t(:caravan_site)
              %td(style="width:25%;")
                = t(:occupied_public_space)
              %td(style="width:25%;")
                = t(:evicted)

app/views/shared/_menu.html.haml
%nav.navbar.navbar-default.navbar-static-top#header
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: :button, data: { toggle: :collapse, target: "#main-nav-inner" } }
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Squatting Europe Kollective", root_path, class: "navbar-brand"
    .collapse.navbar-collapse#main-nav-inner
      %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{ href: '', role: :button, data: { toggle: :dropdown }, aria: { expanded: :false } }
            = City.model_name.human(count: 2)
            %span.caret
          %ul.dropdown-menu{ role: :menu }
            %li= link_to t(:menu_cities), root_path
            %li.divider
            - @cities.by_name.each do |city|
              %li= link_to city.menu_name, city_squats_path(city)
            - if can? :create, City
              %li.divider
              %li= link_to t(:new_city), new_city_path
        - if content_for?(:menu_left)
          = yield(:menu_left)
      %ul.nav.navbar-nav.navbar-right
        - if content_for?(:menu_right)
          = yield(:menu_right)
        %li.dropdown
          %a.dropdown-toggle{ href: '', role: :button, data: { toggle: :dropdown }, aria: { expanded: :false } }
            %i.glyphicon.glyphicon-globe
            %span.caret
          %ul.dropdown-menu{ role: :menu }
            - I18n.available_locales.each do |l|
              %li{ class: (l.to_s + " language-selector") }
                = link_to language_for(l), locale: l
        - if can? :manage, User
          %li= link_to User.model_name.human(count: 2), users_path
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{ href: '', role: :button, data: { toggle: :dropdown }, aria: { expanded: :false } }
              = t(:account)
              %span.caret
            %ul.dropdown-menu{ role: :menu }
              %li
                = link_to t(:edit), edit_user_registration_path
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Login', new_user_session_path

app/views/shared/_versions.html.haml
- if can? :read, PaperTrail::Version
  %h3= t(:previous_versions)

  %table.table.table-striped
    %thead
      %tr
        %th= t(:version_id)
        %th= t(:version_created_at)
        %th= User.model_name.human
        %th.version-diff= t(:diff)
        %th= t(:actions)
    %tbody
      - record.versions.each do |version|
        %tr
          %td= version.id
          %td= version.created_at
          %td= User.find(version.whodunnit).email unless version.whodunnit.nil?
          %td.version-diff
            .show-diff.btn.btn-default
              = t(:show_diff)
            %pre= simple_format(JSON.pretty_generate(version.changeset))
          %td
            .btn-group
              = link_to t(:show), version_city_squat_path(@city, @squat, version.id), class: "btn btn-default"
              = link_to t(:revert_to_version), revert_to_version_city_squat_path(@city, @squat, version.id), class: "btn btn-default"